apiVersion: apps/v1
kind: Deployment
metadata:
  name: FlaskApp
spec:
  replicas: 3 # Number of replicas you want to run
  selector:
    matchLabels:
      app: FlaskApp
  template:
    metadata:
      labels:
        app: FlaskApp
    spec:
      containers:
        - name: FlaskApp
          image: anantha3267/flaskapp:83
          ports:
            - containerPort: 5000 # Port your application is listening on
