apiVersion: v1
kind: Service
metadata:
  name: FlaskApp-service
spec:
  selector:
    app: FlaskApp
  ports:
    - protocol: TCP
      port: 5000 # Port to expose on the service
      targetPort: 5000 # Port your application is listening on
  type: NodePort
